[build]
  command = """
    curl -sfL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh -s -- -b /usr/local/bin &&
    vale sync &&
    vale content/ &&
    hugo
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.7"

[[redirects]]
  from = "/blogroll"
  to = "/blogroll.xml"
  status = 301
  force = true

[[redirects]]
  from = "/podroll"
  to = "/podroll.xml"
  status = 301
  force = true