[build]
  command = """
    pip install vale &&
    vale sync &&
    vale content/ || true &&
    hugo
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.7"

[[redirects]]
  from = "/blogroll"
  to = "/blogroll.xml"
  status = 301
  force = true

[[redirects]]
  from = "/podroll"
  to = "/podroll.xml"
  status = 301
  force = true